# Generated by Django 4.2.1 on 2023-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('content', models.TextField(max_length=15000, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изображение')),
                ('date_of_creation', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('sign_of_publication', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ('record_title', 'slug', 'date_of_creation', 'sign_of_publication'),
            },
        ),
    ]
