# Generated by Django 4.2.1 on 2023-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_record_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
