# Generated by Django 4.2.1 on 2023-05-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_record_number_of_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='number_of_views',
            new_name='views',
        ),
    ]
